[package]
name = "solana-escrow"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
arrayref = "0.3.6"
spl-token = {version = "3.1.1", features = ["no-entrypoint"]}
solana-program = "1.6.9"
thiserror = "1.0.24"


[lib]
crate-type = ["cdylib", "lib"]